spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lgi_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 2022
  #    initialization-mode: always
  #   sql-script-encoding: UTF-8
  security:
    user:
      name: fooding
      password: fooding
      role: USER
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  #    defer-datasource-initialization: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  server:
    session:
      cookie:
        secure: true