spring:
  datasource:
    url: jdbc:mysql://13.124.207.219:3306/lgi_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 2022
#  security:
##    require-ssl: true
#    user:
#      name: fooding
#      password: fooding
#      role: USER
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  defer-datasource-initialization: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false