spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample_project?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 2022
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace