spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sample_project
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: fooding
      password: fooding
      role: USER
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#  defer-datasource-initialization: true
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
jackson:
  serialization:
    FAIL_ON_EMPTY_BEANS: false
jwt:
  header: Authorization
  secret: secretasdfasdfAasdfSDFSl1231HALSKDJFHAasdasdfkasdlfkjasdflkjahewlkjhrlkj2l1kj3h4lkjhasldkjfhalskdjfh
  token-validity-in-seconds: 86400