spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sample_project
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
#    require-ssl: true
    user:
      name: fooding
      password: fooding
      role: USER
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  defer-datasource-initialization: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false