spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sample_project
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: fooding
      password: foodingpw
      role: USER, ADMIN
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false